default: &default
  encoding: utf8
  adapter: mysql2
  database: dev
  username: wj8a9k3cvqabgosbxnhy
  host: aws-eu-west-2.connect.psdb.cloud
  password: pscale_pw_79KDOqVvrOhMsoOghadBoWwxicoBd5wYhHVAdA7nkw0
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

production:
  <<: *default

