default: &default
  encoding: unicode
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/dev.sqlite

production:
  <<: *default
  database: db/prod.sqlite

