default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: doadmin
  password: AVNS_OWMH6imrzCthYk614w7
  host: dev-db-do-user-13580058-0.b.db.ondigitalocean.com
  port: 25060
  database: db_5d90a414031e
  sslmode: require

production:
  <<: *default
  username: doadmin
  password: AVNS_OWMH6imrzCthYk614w7
  host: dev-db-do-user-13580058-0.b.db.ondigitalocean.com
  port: 25060
  database: db_5d90a414031e
  sslmode: require
