default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: dev
  password: dev

production:
  <<: *default
  username: dev
  password: dev
