default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: user_45cee60f5b86
  password: AVNS_FU4QXU37P_ZrdX1Daet
  database: db_5d90a414031e
  sslmode: require

production:
  <<: *default
  username: user_45cee60f5b86
  password: AVNS_FU4QXU37P_ZrdX1Daet
  database: db_5d90a414031e
  sslmode: require
